; PlatformIO — ESP32 Rover Firmware v2
; Flash: pio run --target upload --upload-port /dev/ttyESP32

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    https://github.com/micro-ROS/micro_ros_arduino.git#humble

upload_speed = 115200
monitor_speed = 115200

upload_flags =
    --before=no_reset

board_build.partitions = huge_app.csv

build_flags =
    -L .pio/libdeps/esp32dev/micro_ros_arduino/src/esp32
    -l microros
